"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 15:36:56.809621
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('repository_url', sa.String(length=512), nullable=False),
    sa.Column('repository_name', sa.String(length=256), nullable=False),
    sa.Column('branch', sa.String(length=256), nullable=False),
    sa.Column('analysis_depth', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('enable_github_actions', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('repo_profile', sa.JSON(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('execution_summary', sa.JSON(), nullable=False),
    sa.Column('overall_risk_score', sa.Float(), nullable=True),
    sa.Column('overall_risk_level', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_status'), ['status'], unique=False)

    op.create_table('action_proposals',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('patch', sa.Text(), nullable=True),
    sa.Column('target_repository', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_action_proposals_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_proposals'))
    )
    with op.batch_alter_table('action_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_proposals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_proposals_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_proposals_status'), ['status'], unique=False)

    op.create_table('agent_runs',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=48), nullable=False),
    sa.Column('strategy', sa.String(length=48), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=48), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('parent_request_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_agent_runs_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)

    op.create_table('correlations',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('finding_ids', sa.JSON(), nullable=False),
    sa.Column('relationship_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_multiplier', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_correlations_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correlations'))
    )
    with op.batch_alter_table('correlations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correlations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_correlations_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_correlations_relationship_type'), ['relationship_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_correlations_signature'), ['signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_correlations_status'), ['status'], unique=False)

    op.create_table('execution_events',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=64), nullable=False),
    sa.Column('receiver', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_execution_events_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_events')),
    sa.UniqueConstraint('investigation_id', 'seq', name=op.f('uq_execution_events_investigation_id_seq'))
    )
    with op.batch_alter_table('execution_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_events_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_events_sender'), ['sender'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('findings',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('rule_id', sa.String(length=96), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_factors', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('affected_files', sa.JSON(), nullable=False),
    sa.Column('affected_components', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('tool_results', sa.JSON(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('is_hypothesis', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_findings_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_subject'), ['subject'], unique=False)

    op.create_table('investigation_requests',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('target_agent', sa.String(length=64), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('required_evidence', sa.String(length=64), nullable=False),
    sa.Column('focus', sa.JSON(), nullable=False),
    sa.Column('related_finding_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('assigned_task_ids', sa.JSON(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_requests_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_requests'))
    )
    with op.batch_alter_table('investigation_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigation_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigation_requests_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigation_requests_status'), ['status'], unique=False)

    op.create_table('recommendations',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('risk_id', sa.String(length=36), nullable=True),
    sa.Column('finding_ids', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('affected_component', sa.String(length=512), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('proposed_fix', sa.Text(), nullable=False),
    sa.Column('estimated_risk', sa.JSON(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('expected_benefit', sa.Text(), nullable=False),
    sa.Column('implementation_difficulty', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_recommendations_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_priority'), ['priority'], unique=False)

    op.create_table('risks',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('exploitability', sa.Float(), nullable=False),
    sa.Column('correlation_multiplier', sa.Float(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('member_finding_ids', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_risks_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risks'))
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_severity'), ['severity'], unique=False)

    op.create_table('evidence',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('file', sa.String(length=1024), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=False),
    sa.Column('raw_reference', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_evidence_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_evidence_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('verifications',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('challenge', sa.Text(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('evidence_checked', sa.JSON(), nullable=False),
    sa.Column('additional_tests', sa.JSON(), nullable=False),
    sa.Column('counter_evidence', sa.JSON(), nullable=False),
    sa.Column('adjusted_severity', sa.String(length=16), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['correlation_id'], ['correlations.id'], name=op.f('fk_verifications_correlation_id_correlations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_verifications_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_verifications_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications'))
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verifications_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_verified_at'), ['verified_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verifications_verified_at'))
        batch_op.drop_index(batch_op.f('ix_verifications_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_finding_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_decision'))
        batch_op.drop_index(batch_op.f('ix_verifications_correlation_id'))

    op.drop_table('verifications')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_finding_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_created_by'))
        batch_op.drop_index(batch_op.f('ix_evidence_created_at'))

    op.drop_table('evidence')
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risks_severity'))
        batch_op.drop_index(batch_op.f('ix_risks_priority'))
        batch_op.drop_index(batch_op.f('ix_risks_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_risks_finding_id'))
        batch_op.drop_index(batch_op.f('ix_risks_created_at'))

    op.drop_table('risks')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_priority'))
        batch_op.drop_index(batch_op.f('ix_recommendations_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_created_at'))

    op.drop_table('recommendations')
    with op.batch_alter_table('investigation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_requests_status'))
        batch_op.drop_index(batch_op.f('ix_investigation_requests_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_investigation_requests_created_at'))

    op.drop_table('investigation_requests')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_subject'))
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_findings_created_at'))
        batch_op.drop_index(batch_op.f('ix_findings_category'))
        batch_op.drop_index(batch_op.f('ix_findings_agent'))

    op.drop_table('findings')
    with op.batch_alter_table('execution_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_execution_events_sender'))
        batch_op.drop_index(batch_op.f('ix_execution_events_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_execution_events_event_type'))

    op.drop_table('execution_events')
    with op.batch_alter_table('correlations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correlations_status'))
        batch_op.drop_index(batch_op.f('ix_correlations_signature'))
        batch_op.drop_index(batch_op.f('ix_correlations_relationship_type'))
        batch_op.drop_index(batch_op.f('ix_correlations_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_correlations_created_at'))

    op.drop_table('correlations')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('action_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_action_proposals_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_action_proposals_created_at'))

    op.drop_table('action_proposals')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_status'))
        batch_op.drop_index(batch_op.f('ix_investigations_created_at'))

    op.drop_table('investigations')
    # ### end Alembic commands ###
